# -*- coding: utf-8 -*-
"""lloro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bI0H0p8IQ9ztz30eIeXgvyzXJmj0fWEU
"""

# Para que se pueda programar en streamlit
import streamlit as st

#Las variables de los str y la ubicación del texto mediante el .title y . markdown y st que es un comando especial de streamlit

t=("Sufriendo por primera vez con Pyhton")
st.title(t)

p1 = "Hola, soy Sebastian Villalobos Zender, les voy a contar mi experiencia programamando con python"

st.markdown(p1)
#este de aquí es para colocar la imagen
st.image("https://bakhtiarnia.com/assets/images/Hello%20World/hello-world.svg", width=360)

#Las variables de los str y la ubicación del texto mediante el .title y . markdown y st que es un comando especial de streamlit

p2 = "Aprender Python este ciclo fue una nueva experiencia  en donde cometí muchos errores y me divertí intentado hace que mis programas corran como deben.Tengo que decir que al comienzo fue “sencillo” hasta que descubrí la existencia de los bucles “for” y “while”, que aunque entendí el concepto su estructura me hacía la vida imposible pero ahora los comprendo un poco mejor, que al comienzo. Sin embargo apareció otro concepto que hace que me maree un poco que serían los diccionarios que tenían una sintaxis distinta pero similar con las listas (todavía la sufro un poco)."

p3 = " Aun así aprender lenguaje python fue divertido porque me obligo a hacer toda clase de acrobacias mentales para que los programas funcionen. Asimismo y para finalizar, puedo decir que me llevo del curso entender la complejidad y lo que hay detrás de ellas además de aprender a leer los códigos que antes me parecía una lengua muerta recién descubierta…Espero haber entendido bien  "

st.markdown(p2)

st.markdown(p3)